//
//  DogsListInteractor.swift
//  CleanWithNetworking
//
//  Created by EightSquare on 1/31/18.
//  Copyright (c) 2018 EightSquare. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


// MEDIATOR BETWEEN PRESENTER AND WORKER

import UIKit

protocol DogsListBusinessLogic
{
    func fetchData(request: DogsList.FetchData.Request)
}

protocol DogsListDataStore
{
    //var name: String { get set }
}

class DogsListInteractor: DogsListBusinessLogic, DogsListDataStore
{
    var presenter: DogsListPresentationLogic?
    var worker: DogsListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchData(request: DogsList.FetchData.Request)
    {
        worker = DogsListWorker()
        worker?.fetchDataFromWeb {[] (fetchedData) in
            // NOTE: Pass the result to the Presenter
            let response = DogsList.FetchData.Response(dogApi: fetchedData as! DogApi)
            self.presenter?.presentFetchedData(response: response)
        }
    }
}
