//
//  DogsListRouter.swift
//  CleanWithNetworking
//
//  Created by EightSquare on 1/31/18.
//  Copyright (c) 2018 EightSquare. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DogsListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DogsListDataPassing
{
  var dataStore: DogsListDataStore? { get }
}

class DogsListRouter: NSObject, DogsListRoutingLogic, DogsListDataPassing
{
  weak var viewController: DogsListViewController?
  var dataStore: DogsListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: DogsListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: DogsListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
